### ISSUE TITLE
Example comment for protoc-gen-prost-crate insertion point is not preserved at docs.rs

### ISSUE THREAD

**Issue by jaskij** [neoeinstein/protoc-gen-prost#1]
docs.rs:
![image](https://user-images.githubusercontent.com/1429132/160881623-780c40bf-6888-4e72-844e-96f621a5bb9b.png)
GitHub:
![image](https://user-images.githubusercontent.com/1429132/160881656-f563c1ba-ec24-43c0-a513-fda136c4bb7c.png)

**Comment by neoeinstein** [comment]
Oooh. Interesting. That's because it's also the rustdoc "nothing to see here" sentinel value for hiding code that must exist, but shouldn't be shown. Will see if I can get that to appear.

**Comment by neoeinstein** [comment]
Fixed in protoc-gen-prost-crate-v0.1.3. Thanks!
![bildo](https://user-images.githubusercontent.com/18165/160928162-5d1e5e2a-a8ef-42f1-982f-e38ed5c97bec.png)
