### ISSUE TITLE
Representation of non-optional message fields

### ISSUE THREAD

**Issue by tstirrat15** [neoeinstein/protoc-gen-prost#109]
My understanding of protobuf is that every field is optional in the wire format. The `optional` keyword in `proto3` is designed to disambiguate presence - the difference between an empty field in the wire format and a missing field in the wire format.

This doesn't seem to line up with how this library generates `struct`s for messages - every field is required unless explicitly marked as `optional`. Is there a reason for that? Is there another way of generating the structs that better matches the semantics of protobuf?

**Comment by tstirrat15** [comment]
Another way of saying this: in protobuf, the lack of the `optional` keyword doesn't mean the field is required.

**Comment by neoeinstein** [comment]
I don't see any issues with how Prost is generating its structs. Do you have a specific example of a struct where you were expecting to be able to omit a value?

I'll note that _Rust_ doesn't have the same "missing is default" semantics that Go has, so primitives, such as integers, booleans, and strings will be "required" when working with them in Rust, but when they equal their defaults, don't show up in wire serialization.

So, for such primitives, you can use `Default::default()` if you're instantiating them in Rust code. This then also applies in deserialization. If the primitive field is missing, then Prost will assign it as `Default::default()`.

**Comment by tstirrat15** [comment]
Ahhh, that makes sense. I was missing that piece of the instantiation puzzle when a user was asking me about this, and I'm not familiar with Rust generally or this library specifically. Thank you for clarifying!
