### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by UebelAndre** [neoeinstein/protoc-gen-prost#18]
@neoeinstein Hey, would it be possible to get a new release on crates.io that includes https://github.com/neoeinstein/protoc-gen-prost/pull/17 ?

**Comment by diceride** [comment]
@neoeinstein

**Comment by diceride** [comment]
I've contacted @neoeinstein by email.

**Comment by neoeinstein** [comment]
Release for this is in progress

**Comment by neoeinstein** [comment]
This is now complete. Sorry for the delay, I was on vacation for most of July and forgot to get this out prior to leaving. Thanks for the email to ping my attention, @diceride.
