### ISSUE TITLE
protoc-gen-prost-crate: remove insertion point comment in output

### ISSUE THREAD

**Issue by jaskij** [neoeinstein/protoc-gen-prost#2]
Currently, `protoc-gen-prost-crate` leaves the insertion point comment as-is in the output `Cargo.toml`. It should probably remove it.

**Comment by neoeinstein** [comment]
This is a normal part of how insertion points work with `protoc`. Each individual plugin won't know if it is the last plugin in the pipeline, and `protoc` always preserves the comment after inserting above the comment. In addition, `protoc` only provides a mechanism to insert more things at insertion points, never to remove anything generated, so I can't support this from within the plugin.

In this case, if you really want those comments to disappear, what might be best is to run this command post generation, which will delete any line that includes `@@protoc_insertion_point`:

```shell
find <OUTPUT_DIR> -type f -exec sed -i '' '/@@protoc_insertion_point/d' '{}' ';'
```

**Comment by jaskij** [comment]
Fair enough, I also failed to notice it's a `protoc` thing, and not `protoc-gen-prost-crate` thing.

In the end, I believe that this might usually be updated manually anyway, from the output, so it can easily be also fixed manually. And I personally decided not to use `protoc-gen-prost-crate` anyway, after more evaluation.
