### ISSUE TITLE
clippy lint failure when using Rust 1.63.0

### ISSUE THREAD

**Issue by o-agassizii** [neoeinstein/protoc-gen-prost#26]
Hi,

In Rust 1.63.0 there is a new clippy lint https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq

This lint will complain about types that derive PartialEq and could implement Eq. See aforementioned link for details.

Currently, protoc-gen-prost will generate code that derives PartialEq but not Eq even though it could and that triggers this clippy lint.

Example:

```text
error: you are deriving `PartialEq` and can implement `Eq`
 --> somefile.rs:3:17
  |
3 | #[derive(Clone, PartialEq, ::prost::Message)]
  |                 ^^^^^^^^^ help: consider deriving `Eq` as well: `PartialEq, Eq`
  |
  = note: `-D clippy::derive-partial-eq-without-eq` implied by `-D warnings`
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq
```

It is sometimes common to treat clippy warnings as errors. At my company we do, so currently this is causing CI failure for us.

Is this issue arising from protoc-gen-prost? If not, please let me know where I should file this issue instead.

**Comment by o-agassizii** [comment]
Minimal reproducible example:

Assuming `protoc`, `buf`, `protoc-gen-prost` and Rust toolchain version 1.63.0 have already been installed.

```zsh
protoc --version
```

```text
libprotoc 3.20.1
```

```zsh
buf --version
```

```text
1.7.0
```

```zsh
protoc-gen-prost --version
```

```text
0.2.0
```

```zsh
cargo version
```

```text
cargo 1.63.0 (fd9c4297c 2022-07-01)
```

Then clone the protoc-gen-prost repo so that we can use one of the code generation examples from there.

```zsh
mkdir -p ~/tmp/github.com/neoeinstein
cd ~/tmp/github.com/neoeinstein
git clone https://github.com/neoeinstein/protoc-gen-prost.git
cd protoc-gen-prost/example/build-with-buf
```

```zsh
buf generate
```

```zsh
cargo clippy --all --all-targets --all-features -- -Dwarnings -Drust-2018-idioms
```

We see the new clippy lint `derive_partial_eq_without_eq` is triggered.

```text
[...]
Checking build-with-buf v0.1.0 (/Users/o-agassizii/tmp/github.com/neoeinstein/protoc-gen-prost/example/build-with-buf)
error: you are deriving `PartialEq` and can implement `Eq`
 --> src/gen/example.rs:2:17
  |
2 | #[derive(Clone, PartialEq, ::prost::Message)]
  |                 ^^^^^^^^^ help: consider deriving `Eq` as well: `PartialEq, Eq`
  |
  = note: `-D clippy::derive-partial-eq-without-eq` implied by `-D warnings`
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq

error: you are deriving `PartialEq` and can implement `Eq`
 --> src/gen/example.rs:7:17
  |
7 | #[derive(Clone, PartialEq, ::prost::Message)]
  |                 ^^^^^^^^^ help: consider deriving `Eq` as well: `PartialEq, Eq`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq

error: could not compile `build-with-buf` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `build-with-buf` due to 2 previous errors
```

**Comment by o-agassizii** [comment]
Even though most people may not run clippy lint warnings as errors, it seems to me that it would be desirable for the code generated by `protoc-gen-prost` to adhere to this lint.

**Comment by neoeinstein** [comment]
Nearly all of the actual code generation done by `protoc-gen-prost` and similar crates is delegated to underlying code generators. In this case, it will have been `prost-build` that produced these. Back when this new lint was on nightly, an issue was posted to the `prost` repository. You can read the response there: tokio-rs/prost#661

The recommendation seems to be to add an `#[allow(clippy::derive_partial_eq_without_eq)]` onto the crate or module where you're including the generated code.
