### ISSUE TITLE
Custom file output format

### ISSUE THREAD

**Issue by hexfusion** [neoeinstein/protoc-gen-prost#27]
As per the docs:

```
A package named helloworld.abstract.v1 will have an output filename of helloworld.abstract.v1.rs.
```
While this is  a nice readable format  having a dot in the file name makes it incompatible with rust for use directly with `mod`. The result is we are required to use `include` macro. But IDE's such as vscode with rust extension are unable to reference the definition for traits etc. This is sort of a big deal for developer UX.

If we allowed the separator to be configurable IE `_`  `helloworld_abstract_v1.rs.` would be valid. That would allow the below which also allows visibility into the trait source via IDE.

```
mod helloworld_abstract_v1;
mod helloworld_abstract_v1_tonic;

#[cfg(feature = "helloworld")]
pub mod helloworld {
    pub use super::helloworld_abstract_vs::*
    pub use super::helloworld_abstract_vs_tonic::*
}
```
I imagine this would mess with your prost-crate assumptions so perhaps we could gate this an not compatible? Or better yet we could adopt this output? :)

**Comment by neoeinstein** [comment]
Much of this goes back to how `prost-build` is set up to generate these files. It makes certain assumptions about the module structure between various elements, and `protoc-gen-prost-crate` uses those conventions in setting up the includes.

In my case, I regularly use _Visual Studio Code_ with the _rust-analyzer_ plugin, and I don't seem to have the same issue that you appear to be indicating you have. I tried this in two fashions, from within and without the same crate where the definitions are being included, and I had no problems getting VSCode to bring up the trait methods:

<img width="793" alt="image" src="https://user-images.githubusercontent.com/18165/185770758-84d89c8b-1235-4059-a757-ba37d2fc4e13.png">

Of note, the `rust-analyzer` plugin filters out functions for traits that aren't in scope. Thus, when I just press `.` without having `prost::Message` imported, I only see the following:

<img width="733" alt="image" src="https://user-images.githubusercontent.com/18165/185770777-8c33fc17-e8ea-4fe5-89b5-372a1e3d6a5a.png">

But, if I have already imported `prost::Message` into the file with `use prost::Message`, then I see this:

<img width="751" alt="image" src="https://user-images.githubusercontent.com/18165/185770787-94988aaf-aaac-4e2b-be05-82e39731d071.png">

If you're more worried about the fact that "Go to definition" leads you to the `include!()` macro invocation, that is a limitation of _rust-analyzer_ (rust-lang/rust-analyzer#3767 and rust-lang/rust-analyzer#9403). I'm not keen to add and support a new feature just to work around a tooling issue that should be fixed on that side.

**Comment by neoeinstein** [comment]
> While this is a nice readable format having a dot in the file name makes it incompatible with rust for use directly with `mod`.

Note that if you want this, you can specify the path manually with an attribute:

```rust
#[path = "helloworld.abstract.v1.rs"]
mod helloworld_abstract_v1;
```

**Comment by hexfusion** [comment]
Everything for the most part works fine with vscode but if I do `[go to definition]` I always land on the root include. Which I guess we can't completely blame on the implementation. I appreciate the feedback.

<img width="136" alt="image" src="https://user-images.githubusercontent.com/1249749/185770979-8c4e1b51-96c1-44bf-8aa6-11552d1b0866.png">

**Comment by hexfusion** [comment]
> > While this is a nice readable format having a dot in the file name makes it incompatible with rust for use directly with `mod`.
> 
> Note that if you want this, you can specify the path manually with an attribute:
> 
> ```rust
> #[path = "helloworld.abstract.v1.rs"]
> mod helloworld_abstract_v1;
> ```

Nice this actually helps me a lot, had not tried that. Will close this as we have a viable workaround. Thanks!
