### ISSUE TITLE
[BUG] Insertions overwrite each other

### ISSUE THREAD

**Issue by stan-sack** [neoeinstein/protoc-gen-prost#40]
Hi, I'm trying to compile two unrelated proto files using protoc-gen-prost to create two separate modules but im finding that each separate invocation of `protoc` overwrites the generated lib.rs and Cargo.toml file rather than update in place. 

My use case is a monorepo where the protos for many services are stored in /protos/<service-name> and the output goes in /generated/<langauge>.

I have put together a minimal reproduction in [this repo](https://github.com/stan-sack/prost-repro)

You can see that I have two proto files:
- [protos/foo/foo.proto](https://github.com/stan-sack/prost-repro/blob/main/protos/foo/foo.proto)
- [protos/bar/bar.proto](https://github.com/stan-sack/prost-repro/blob/main/protos/bar/bar.proto)

I'm compiling these with the following commands in the script [generate.sh](https://github.com/stan-sack/prost-repro/blob/main/generate.sh):
```
protoc \
    --prost_out=generated/rust \
    --tonic_out=generated/rust \
    --prost-crate_out=generated/rust \
    --prost-crate_opt=gen_crate=templates/Cargo.toml \
    protos/foo/foo.proto

protoc \
    --prost_out=generated/rust \
    --tonic_out=generated/rust \
    --prost-crate_out=generated/rust \
    --prost-crate_opt=gen_crate=templates/Cargo.toml \
    protos/bar/bar.proto
```

and the generated [lib.rs](https://github.com/stan-sack/prost-repro/blob/main/generated/rust/src/lib.rs) and [Cargo.toml](https://github.com/stan-sack/prost-repro/blob/main/generated/rust/Cargo.toml) dont contain any references to `Foo`:
```
// @generated
pub mod proto {
    #[cfg(feature = "proto-bar")]
    // @@protoc_insertion_point(attribute:proto.bar)
    pub mod bar {
        include!("proto.bar.rs");
        // @@protoc_insertion_point(proto.bar)
    }
}
```

and 
```
[package]
name = "protos"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.11.2"

[features]
default = []
# @@protoc_deletion_point(features)
# This section is automatically generated by protoc-gen-prost-crate.
# Changes in this area may be lost on regeneration.
proto_full = ["proto-bar"]
"proto-bar" = []
## @@protoc_insertion_point(features)
```

If I only run the first protoc command I can see that the `foo` insertions are generated correctly.

I think this is a bug and not a problem with a way I'm using the tool.

Thanks for your hard work here

**Comment by neoeinstein** [comment]
Hey @stan-sack. I notice that you are using two distinct invocations of `protoc` while using the `protoc-gen-crate` plugin. In order to create the common `lib.rs` and crate, `protoc-gen-crate` needs to have a view of all of the files that you are generating at once. This is done by placing all of the files into the same `protoc` invocation. Try this instead:

```sh
protoc \
    --prost_out=generated/rust \
    --tonic_out=generated/rust \
    --prost-crate_out=generated/rust \
    --prost-crate_opt=gen_crate=templates/Cargo.toml \
    protos/foo/foo.proto \
    protos/bar/bar.proto
```

This is called out in the `buf` context as it requires the `all` strategy when used as a `buf` generator, but I don't know that I clearly documented that in the `protoc` case.

Let me know if that resolves the issues you were having.

**Comment by stan-irl** [comment]
perfect. thanks for that. I've been using proto for years and never knew that you could pass a list of proto files.

**Comment by stan-sack** [comment]
perfect. thanks for that! I've been using proto for years and never knew that you could pass a list of proto files
