### ISSUE TITLE
[feature] version sub command

### ISSUE THREAD

**Issue by hexfusion** [neoeinstein/protoc-gen-prost#5]
For build scripts and testing its important to understand what version of the plugin is being used.
```
protoc-gen-prost --version
```

ref.
```
$ protoc-gen-go --version
protoc-gen-go v1.28.0
```

**Comment by hexfusion** [comment]
If I get some time in the next couple weeks I will try and add this.

**Comment by neoeinstein** [comment]
This would be a great addition; definitely agree about being able to have the version print out. If you don't get to it, I'll be sure to add a simple means of doing this in my next release.
