### ISSUE TITLE
add max message size configuration to generated service

### ISSUE THREAD

**Issue by Lev1ty** [neoeinstein/protoc-gen-prost#67]
max request message size is 4MB by default in tonic's 0.9.0 release https://github.com/hyperium/tonic/pull/1337
currently, this size is not configurable from protoc-gen-tonic since it depends on tonic-build 0.8.x
a version bump should catch the codegen up

**Comment by neoeinstein** [comment]
I think I can do this, with a caveat that it will be a breaking change because the generated code will now rely on a `tonic` 0.9.0 feature. That's not a problem, just something that I'll need to call out when cutting a new release with this update included.
