### ISSUE TITLE
Update generation to prost 0.12

### ISSUE THREAD

**Issue by neoeinstein** [neoeinstein/protoc-gen-prost#80]
In general, these crates continue to generate code fine without relying on the newest version of Prost. However, the latest version of Prost adds some interesting new functionality into the generation, so we should look to update to work with that.

May also include updates to the latest version of tonic as well.

**Comment by neekolas** [comment]
Upgrading to the latest version of Tonic would be really great

**Comment by listepo** [comment]
Any news?

**Comment by mmizutani** [comment]
New versions of the code generators have been released.

> Updated code generation for latest tonic (0.11), prost (0.12), and pbjson (0.6)

https://github.com/neoeinstein/protoc-gen-prost/blob/main/CHANGELOG.md#2024-02-15

**Comment by sachaw** [comment]
Any news on 0.13?

**Comment by neoeinstein** [comment]
This has now been released. Thanks @mbrobbel for your help!
